version: "3"

services:
  db:
    container_name: alocacao-celula-db-dev
    image: mysql:5.7
    networks:
      - network-back-dev
    environment:
      MYSQL_DATABASE: alocacao_celula
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: alocacao
  celula-alocacao:
    container_name: backend-ambiente-dev
    image: celula_alocacao_dev:build_${BUILD_NUMBER}
    build:
      context: .
      args:
        - JAR_FILE=target/celula-alocacao.jar
    ports:
      - 8081:8080
    networks:
      - network-back-dev
    environment:
      - PROFILES_ACTIVE=dev
      - STRATEGY_DB=create
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=alocacao
      - DATABASE_NAME=alocacao_celula
      - DATABASE_PORT=3306
    depends_on:
      - db
networks:
  network-back-dev: