version: "3"

services:
  celula-alocacao:
    build:
      context: .
      dockerfile: Dockerfile
    image: celula-alocacao
    ports:
      - 8081:8080
    depends_on:
      - db
    networks:
      - network-back
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=alocacao
      - DATABASE_NAME=alocacao_celula
      - DATABASE_PORT=3306
  db:
    container_name: alocacao-celula-db
    image: mysql:5.7
    networks:
      - network-back
    environment:
      MYSQL_DATABASE: alocacao_celula
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: alocacao

networks:
  network-back: