
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${STRATEGY_DB:create}
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3305}/${DATABASE_NAME:alocacao_celula}?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:alocacao}

  jackson:
    deserialization.fail-on-unknown-properties: true