spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: ${STRATEGY_DB}
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:mysql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWORD:alocacao}

  jackson:
    deserialization.fail-on-unknown-properties: true